### ISSUE TITLE
Implement Debug trait

### ISSUE THREAD

**Issue by skorokithakis** [timvisee/version-compare#10]
Is it possible to implement the Debug trait and possibly a `to_str` version (or similar) so we can print the version or get it back as a string?

**Comment by timvisee** [comment]
Currently, the `Version` struct doesn't really store the literal version number, just the version components (currently, just being the numbers). The `Debug` implementation could chain these together with `.` in between, but that doesn't necessarily produce the original version string. I hope what I'm saying is understandable. Would that be a problem?

Note that I would like to revamp this library in the future, to produce a better API spec, more features, better tests and so on. Maybe this would be something to look at then.

**Comment by skorokithakis** [comment]
That's not a problem, I just want to print the version for debug purposes in that case. Producing something similar is fine, thanks!

**Comment by timvisee** [comment]
Cool. I think I can implement that tomorrow (going to bed now), it shouldn't be too hard.

**Comment by skorokithakis** [comment]
That would be great, thank you!

**Comment by timvisee** [comment]
I was wrong, apparently (it has been a while). There already is an [`as_str()`](https://docs.rs/version-compare/0.0.6/version_compare/version/struct.Version.html#method.as_str) function available on `Version`, and the `Version` struct keeps a reference to the original version number. It does currently not implement `Display` or `Debug` though, which is something I'll be implementing now.

**Comment by skorokithakis** [comment]
Ah, thank you. I'm actually being blocked by #12 right now, where versions are calculated wrong and my entire program doesn't work as a result :(

**Comment by timvisee** [comment]
I've just pushed an update solving these issues, which includes an implementation for `Display` and `Debug` on [`Version`](https://docs.rs/version-compare/0.0.7/version_compare/version/struct.Version.html#implementations).

This is part of `v0.0.7` which I've just pushed to crates.io.

**Comment by skorokithakis** [comment]
That's amazing, thank you!
