### ISSUE TITLE
Improve library usability

### ISSUE THREAD

**Issue by skorokithakis** [timvisee/version-compare#11]
Right now it's very hard to use the library because there's a reference in Version, so I can't keep a Version longer than its parent str is alive for. I'm not sure how this can be fixed, but the good people of #rust-beginners had many suggestions which flew a bit over my head, but you might want to ask them.

**Comment by timvisee** [comment]
You're right.

The `Version` struct takes a reference to the version string to prevent cloning as much as possible.
I therefore recommend you to keep (own) the version numbers, and not the `Version` structs. It might be easier to use the functions on [`VersionCompare`](https://docs.rs/version-compare/0.0.7/version_compare/version_compare/struct.VersionCompare.html) which simply accept strings with such approach.

I might look into supporting different options (using references, and owned strings) when I start reworking the library using a trait based system. I currently don't know when I have time for that though, sorry.

I'll close this for now, as it's something that will definitely be addressed when I re-implement the crate. I hope that's understandable. Be sure to open the issue again if you have any other questions regarding this topic.

**Comment by skorokithakis** [comment]
Yeah, that's what I ended up doing, but to select the latest version out of 1000 strings I had to do 2000 parses (one of the candidate and one of the original string again, as I couldn't keep a reference to it). The workaround is fine for me at the moment, thanks!

**Comment by timvisee** [comment]
I see. Yeah, that's definitively a case where a owned `Version` type would be a good option, thanks for mention it. I'll take it into account when redesigning the crate.
