### ISSUE TITLE
Versions are compared wrong

### ISSUE THREAD

**Issue by skorokithakis** [timvisee/version-compare#12]
```
extern crate version_compare;

use version_compare::{CompOp, VersionCompare};

fn main() {
    // Define some version numbers
    let a = "1.1.30-dev";
    let b = "1.1.2";

    // Match
    match VersionCompare::compare(&a, &b).unwrap() {
        CompOp::Lt => println!("Version a is older than b"),
        CompOp::Eq => println!("Version a is equal to b"),
        CompOp::Gt => println!("Version a is newer than b"),
        _ => unreachable!(),
    }
}
```

This prints `Version a is older than b`, which is not the case.

**Comment by timvisee** [comment]
You're correct.

Because version numbers can be infinitely complex, there may be some cases with undefined behavior right now. This is something I'd like to look into and improve when I start reworking this library.

Anyway, I've fixed this issue now in the latest release (`v0.0.7`), which I've just pushed to crates.io.

I've added your example to the automated tests to ensure it keeps working:
https://github.com/timvisee/version-compare/blob/master/src/test/test_version_set.rs#L37

**Comment by skorokithakis** [comment]
I just tested it and it works great, thank you. The only slight problem now is that `1.2.3-dev` is not less than `1.2.3`, but I'm not sure that's easy to sort.

**Comment by timvisee** [comment]
Awesome.

Currently, there is no defined way how strings (for example `dev` and `beta`) are compared to each other. In this case it is about a single string compared to nothing though. I think I can implement that _nothing_  is always greater than a string such as `dev`, which would be your case. I'm wondering however, if there are cases where this shouldn't be true. If there aren't, I think I can implement (fix) that case as well.

In any case, do you have other cases where you believe comparison is incorrect with the current implementation? I might be able to take a look at them too.

**Comment by skorokithakis** [comment]
The comparison seems correct in other cases that I've seen. I think it's always the case that some string is less than no string, but I don't know about 1.2.3-patch1. In my experience, that just tends to be 1.2.3.1.

**Comment by timvisee** [comment]
I've just implemented [_nothing_ `<` _text_]. This behavior might change in the future though, configurable, once manifests are properly implemented.

I've pushed the change including this _fix_ as `v0.0.8`.

**Comment by skorokithakis** [comment]
Fantastic, thanks for being so responsive!
